var annotated_dup =
[
    [ "dummydb", null, [
      [ "CDatabase", "classdummydb_1_1_c_database.html", "classdummydb_1_1_c_database" ],
      [ "CInsertValuesContainer", "classdummydb_1_1_c_insert_values_container.html", "classdummydb_1_1_c_insert_values_container" ],
      [ "CPreparedInsert", "classdummydb_1_1_c_prepared_insert.html", "classdummydb_1_1_c_prepared_insert" ]
    ] ],
    [ "gcp", null, [
      [ "CBucket", "classgcp_1_1_c_bucket.html", "classgcp_1_1_c_bucket" ],
      [ "CCloud", "classgcp_1_1_c_cloud.html", "classgcp_1_1_c_cloud" ],
      [ "CCloudBill", "classgcp_1_1_c_cloud_bill.html", "classgcp_1_1_c_cloud_bill" ],
      [ "CCloudFactory", "classgcp_1_1_c_cloud_factory.html", "classgcp_1_1_c_cloud_factory" ],
      [ "CRegion", "classgcp_1_1_c_region.html", "classgcp_1_1_c_region" ]
    ] ],
    [ "psql", null, [
      [ "CDatabase", "classpsql_1_1_c_database.html", "classpsql_1_1_c_database" ],
      [ "CInsertValuesContainer", "classpsql_1_1_c_insert_values_container.html", "classpsql_1_1_c_insert_values_container" ],
      [ "CPreparedInsert", "classpsql_1_1_c_prepared_insert.html", "classpsql_1_1_c_prepared_insert" ],
      [ "CResult", "classpsql_1_1_c_result.html", null ]
    ] ],
    [ "CBaseOnDeletionInsert", "class_c_base_on_deletion_insert.html", "class_c_base_on_deletion_insert" ],
    [ "CBaseStorageElementDelegate", "class_c_base_storage_element_delegate.html", "class_c_base_storage_element_delegate" ],
    [ "CBaseTransferManager", "class_c_base_transfer_manager.html", "class_c_base_transfer_manager" ],
    [ "CBillingGenerator", "class_c_billing_generator.html", "class_c_billing_generator" ],
    [ "CBufferedOnDeletionInsert", "class_c_buffered_on_deletion_insert.html", "class_c_buffered_on_deletion_insert" ],
    [ "CCachedSrcTransferGen", "class_c_cached_src_transfer_gen.html", "class_c_cached_src_transfer_gen" ],
    [ "CCloudBufferTransferGen", "class_c_cloud_buffer_transfer_gen.html", "class_c_cloud_buffer_transfer_gen" ],
    [ "CCloudFactoryManager", "class_c_cloud_factory_manager.html", "class_c_cloud_factory_manager" ],
    [ "CConfigManager", "class_c_config_manager.html", "class_c_config_manager" ],
    [ "CDataGenerator", "class_c_data_generator.html", "class_c_data_generator" ],
    [ "CDefaultBaseSim", "class_c_default_base_sim.html", "class_c_default_base_sim" ],
    [ "CExponentialRandomValueGenerator", "class_c_exponential_random_value_generator.html", "class_c_exponential_random_value_generator" ],
    [ "CExponentiatedWeibullRandomValueGenerator", "class_c_exponentiated_weibull_random_value_generator.html", "class_c_exponentiated_weibull_random_value_generator" ],
    [ "CFixedTimeTransferManager", "class_c_fixed_time_transfer_manager.html", "class_c_fixed_time_transfer_manager" ],
    [ "CFixedTransferGen", "class_c_fixed_transfer_gen.html", "class_c_fixed_transfer_gen" ],
    [ "CFixedValueGenerator", "class_c_fixed_value_generator.html", "class_c_fixed_value_generator" ],
    [ "CGeometricRandomValueGenerator", "class_c_geometric_random_value_generator.html", "class_c_geometric_random_value_generator" ],
    [ "CGridSite", "class_c_grid_site.html", "class_c_grid_site" ],
    [ "CHCDCTransferGen", "class_c_h_c_d_c_transfer_gen.html", "class_c_h_c_d_c_transfer_gen" ],
    [ "CHeartbeat", "class_c_heartbeat.html", "class_c_heartbeat" ],
    [ "CJobSlotTransferGen", "class_c_job_slot_transfer_gen.html", "class_c_job_slot_transfer_gen" ],
    [ "CMaxClipLimiter", "class_c_max_clip_limiter.html", "class_c_max_clip_limiter" ],
    [ "CMaxModuloLimiter", "class_c_max_modulo_limiter.html", "class_c_max_modulo_limiter" ],
    [ "CMinAddLimiter", "class_c_min_add_limiter.html", "class_c_min_add_limiter" ],
    [ "CMinClipLimiter", "class_c_min_clip_limiter.html", "class_c_min_clip_limiter" ],
    [ "CNetworkLink", "class_c_network_link.html", "class_c_network_link" ],
    [ "CNormalRandomValueGenerator", "class_c_normal_random_value_generator.html", "class_c_normal_random_value_generator" ],
    [ "COutput", "class_c_output.html", "class_c_output" ],
    [ "CPoissonRandomValueGenerator", "class_c_poisson_random_value_generator.html", "class_c_poisson_random_value_generator" ],
    [ "CReaper", "class_c_reaper.html", "class_c_reaper" ],
    [ "CReaperCaller", "class_c_reaper_caller.html", "class_c_reaper_caller" ],
    [ "CReplicaPreRemoveMultiListener", "class_c_replica_pre_remove_multi_listener.html", "class_c_replica_pre_remove_multi_listener" ],
    [ "CRucio", "class_c_rucio.html", "class_c_rucio" ],
    [ "CSchedulable", "class_c_schedulable.html", "class_c_schedulable" ],
    [ "CScopedTimeDiffAdd", "class_c_scoped_time_diff_add.html", null ],
    [ "CScopedTimeDiffSet", "class_c_scoped_time_diff_set.html", null ],
    [ "CStorageElement", "class_c_storage_element.html", "class_c_storage_element" ],
    [ "CTransferManager", "class_c_transfer_manager.html", "class_c_transfer_manager" ],
    [ "CUniqueReplicaStorageElementDelegate", "class_c_unique_replica_storage_element_delegate.html", "class_c_unique_replica_storage_element_delegate" ],
    [ "CWeibullRandomValueGenerator", "class_c_weibull_random_value_generator.html", "class_c_weibull_random_value_generator" ],
    [ "IBaseCloud", "class_i_base_cloud.html", "class_i_base_cloud" ],
    [ "IBaseSim", "class_i_base_sim.html", "class_i_base_sim" ],
    [ "ICloudBill", "class_i_cloud_bill.html", "class_i_cloud_bill" ],
    [ "ICloudFactory", "class_i_cloud_factory.html", "class_i_cloud_factory" ],
    [ "IConfigConsumer", "class_i_config_consumer.html", "class_i_config_consumer" ],
    [ "IDatabase", "class_i_database.html", "class_i_database" ],
    [ "IInsertValuesContainer", "class_i_insert_values_container.html", "class_i_insert_values_container" ],
    [ "IPreparedInsert", "class_i_prepared_insert.html", "class_i_prepared_insert" ],
    [ "IReplicaPreRemoveListener", "class_i_replica_pre_remove_listener.html", "class_i_replica_pre_remove_listener" ],
    [ "IRucioActionListener", "class_i_rucio_action_listener.html", "class_i_rucio_action_listener" ],
    [ "ISite", "class_i_site.html", "class_i_site" ],
    [ "IStorageElementActionListener", "class_i_storage_element_action_listener.html", "class_i_storage_element_action_listener" ],
    [ "IStorageElementDelegate", "class_i_storage_element_delegate.html", "class_i_storage_element_delegate" ],
    [ "IValueGenerator", "class_i_value_generator.html", "class_i_value_generator" ],
    [ "IValueLimiter", "class_i_value_limiter.html", "class_i_value_limiter" ],
    [ "SFile", "struct_s_file.html", "struct_s_file" ],
    [ "SIndexedReplicas", "struct_s_indexed_replicas.html", "struct_s_indexed_replicas" ],
    [ "SReplica", "struct_s_replica.html", "struct_s_replica" ],
    [ "SSchedulePrioComparer", "struct_s_schedule_prio_comparer.html", null ]
];